import {filterDiscussions} from './community-feed.mjs?v=20261003-2';

import{initializeApp}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';import{addDoc,collection,getFirestore,limit,onSnapshot,query,serverTimestamp,where}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
const app=initializeApp({apiKey:'AIzaSyDeuW583lgxl08k-DYDju7jQiZP2jVqUk4',authDomain:'kindred-507209.firebaseapp.com',projectId:'kindred-507209',storageBucket:'kindred-507209.firebasestorage.app',messagingSenderId:'459167088901',appId:'1:459167088901:web:c13b3aeaf9d6e41e9cf76c'}),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider(),$=s=>document.querySelector(s);let user=null;
$('#signIn').onclick=()=>signInWithPopup(auth,provider).catch(e=>alert(e.message));$('#signOut').onclick=()=>signOut(auth);onAuthStateChanged(auth,u=>{user=u;$('#signedOut').classList.toggle('hidden',!!u);$('#postForm').classList.toggle('hidden',!u)});
$('#postForm').onsubmit=async e=>{e.preventDefault();if(!user)return;let text=$('#message').value.trim();if(text.length<10)return;if(!$('#adultConfirm').checked)return;$('#status').textContent='Publishing…';try{await addDoc(collection(db,'forumPosts'),{authorId:user.uid,authorName:user.displayName||'Kindred member',category:$('#category').value,country:$('#country').value.trim().slice(0,60),city:$('#city').value.trim().slice(0,60),text,status:'visible',adultConfirmed:true,createdAt:serverTimestamp()});$('#message').value='';$('#status').textContent='Published.'}catch(x){console.error(x);$('#status').textContent=x?.code==='permission-denied'?'Please confirm you are 18+ and complete the required fields before posting.':'Could not publish this post. Please try again.'}};
const questions=["What helped you feel less like a stranger in a new city?","What is your easiest way to invite someone for a first meetup?","Which hobby has helped you meet people?","What makes a new friendship feel comfortable to you?","What is one place in your city you would recommend to someone new?","Do you prefer coffee, walks or shared activities for a first meetup?","What is the hardest part of making friends as an adult?"];document.getElementById('qotd').textContent=questions[Math.floor(Date.now()/86400000)%questions.length];let allPosts=[],postsLoaded=false;
const liked=id=>{try{return localStorage.getItem('kindredLike:'+id)==='1'}catch{return false}};
const postDate=post=>{const date=post.createdAt?.toDate?.();return date && Number.isFinite(date.getTime())?`<time class="post-date" datetime="${date.toISOString()}">${new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'}).format(date)}</time>`:''};
const render=()=>{
  if(!postsLoaded)return;
  const place=$('#filterCity').value,category=$('#filterCategory').value;
  const posts=filterDiscussions(allPosts,{place,category});
  $('#discussion-count').textContent=`${posts.length} ${posts.length===1?'discussion':'discussions'} shown`;
  document.querySelectorAll('[data-category]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.category===category)));
  $('#topics').innerHTML=posts.length?posts.map(x=>{const place=[x.city,x.country].filter(Boolean).join(', ');return `<article class="topic"><div class="meta">${safe(x.category)}${place?' · '+safe(place):''} · ${safe(x.authorName||'Kindred member')}${postDate(x)}</div><p>${safe(x.text)}</p><div class="actions"><button class="react" data-like="${safe(x.id)}" aria-pressed="${liked(x.id)}">${liked(x.id)?'♥':'♡'} Helpful</button><button class="report" data-report="${safe(x.id)}">Report</button></div></article>`}).join(''):$(place.trim()||category?'#forum-filter-empty':'#forum-empty').innerHTML;
  document.querySelectorAll('[data-like]').forEach(button=>button.onclick=()=>{try{const key='kindredLike:'+button.dataset.like,on=liked(button.dataset.like);on?localStorage.removeItem(key):localStorage.setItem(key,'1');button.textContent=on?'♡ Helpful':'♥ Helpful';button.setAttribute('aria-pressed',String(!on))}catch{alert('This browser could not save your helpful mark.')}});
  document.querySelectorAll('[data-report]').forEach(button=>button.onclick=async()=>{if(!user)return alert('Please sign in to report a post.');const reason=prompt('Why are you reporting this post?');if(!reason||reason.trim().length<5)return;try{await addDoc(collection(db,'forumReports'),{reporterId:user.uid,postId:button.dataset.report,reason:reason.trim().slice(0,500),status:'open',createdAt:serverTimestamp()});alert('Thank you. Your report was submitted.')}catch{alert('Could not submit report.')}});
};$('#filterCity').oninput=render;$('#filterCategory').onchange=render;const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('#resetFilters').onclick=()=>{$('#filterCity').value='';$('#filterCategory').value='';render()};
document.querySelectorAll('[data-category]').forEach(button=>button.onclick=()=>{$('#filterCategory').value=button.dataset.category;render();$('#topics-heading').focus();$('#topics-heading').scrollIntoView({block:'start'})});
onSnapshot(query(collection(db,'forumPosts'),where('status','==','visible'),limit(50)),snap=>{
  allPosts=snap.docs.map(doc=>({...doc.data(),id:doc.id})).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0));postsLoaded=true;render();
},()=>{$('#discussion-count').textContent='Discussions are unavailable right now.';$('#topics').innerHTML=$('#forum-load-error').innerHTML;$('#topics').querySelector('[data-retry]').onclick=()=>location.reload()});
