import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, getFirestore, limit, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, where } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const firebase = initializeApp({apiKey:"AIzaSyDeuW583lgxl08k-DYDju7jQiZP2jVqUk4",authDomain:"kindred-507209.firebaseapp.com",projectId:"kindred-507209",storageBucket:"kindred-507209.firebasestorage.app",messagingSenderId:"459167088901",appId:"1:459167088901:web:c13b3aeaf9d6e41e9cf76c"});
const auth = getAuth(firebase);
const db = getFirestore(firebase);
const provider = new GoogleAuthProvider();
provider.setCustomParameters({prompt:"select_account"});

const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const state = { user:null, profile:null, profiles:new Map(), connections:[], unsubConnections:null, unsubMessages:null, reportTarget:null };

function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),3200)}
function errorMessage(error){console.error(error);const code=error?.code||"";if(code.includes("popup-closed"))return "Sign-in was cancelled.";if(code.includes("permission-denied"))return "This action is not permitted. Please refresh and try again.";if(code.includes("failed-precondition"))return "The community database still needs one Firebase setting.";return "Something went wrong. Please try again."}
function cleanList(value,max){return [...new Set(value.split(",").map(x=>x.trim()).filter(Boolean))].slice(0,max)}
function pairId(a,b){return [a,b].sort().join("_")}
function escapeText(value){const span=document.createElement("span");span.textContent=value||"";return span.innerHTML}
function showPanel(name){$$('[data-panel]').forEach(x=>x.hidden=x.dataset.panel!==name);$$('[data-view]').forEach(x=>x.classList.toggle("active",x.dataset.view===name));if(name==="discover")loadProfiles();if(name==="connections")renderConnections();if(name==="messages")renderConversationList()}
function requireProfile(){if(state.profile)return true;showPanel("profile");toast("Complete your profile first.");return false}

async function signIn(){try{await signInWithPopup(auth,provider)}catch(error){toast(errorMessage(error))}}
async function savePrivateUser(user){await setDoc(doc(db,"users",user.uid),{email:user.email||"",displayName:user.displayName||"Member",photoURL:user.photoURL||"",lastLoginAt:serverTimestamp()},{merge:true})}

async function loadOwnProfile(){const snap=await getDoc(doc(db,"profiles",state.user.uid));state.profile=snap.exists()?snap.data():null;const p=state.profile;if(!p)return showPanel("profile");$("#displayName").value=p.displayName||"";$("#profileCity").value=p.city||"";$("#profileCountry").value=p.country||"";$("#bio").value=p.bio||"";$("#interests").value=(p.interests||[]).join(", ");$("#languages").value=(p.languages||[]).join(", ");$("#availability").value=p.availability||"Flexible";$("#adultConfirm").checked=p.adultConfirmed===true;$("#activeProfile").checked=p.active!==false}

async function saveProfile(event){event.preventDefault();const data={displayName:$("#displayName").value.trim(),city:$("#profileCity").value.trim(),country:$("#profileCountry").value.trim(),bio:$("#bio").value.trim(),interests:cleanList($("#interests").value,12),languages:cleanList($("#languages").value,8),availability:$("#availability").value,photoURL:state.user.photoURL||"",active:$("#activeProfile").checked,adultConfirmed:$("#adultConfirm").checked,updatedAt:serverTimestamp()};if(!data.adultConfirmed||data.bio.length<30||!data.interests.length||!data.languages.length)return toast("Complete every field and confirm that you are 18 or older.");try{await setDoc(doc(db,"profiles",state.user.uid),data);state.profile={...data,updatedAt:new Date()};toast("Profile saved.");showPanel("discover")}catch(error){toast(errorMessage(error))}}

function profileCard(uid,p){const article=document.createElement("article");article.className="person card";const shared=(p.interests||[]).filter(x=>(state.profile?.interests||[]).some(y=>y.toLowerCase()===x.toLowerCase()));article.innerHTML=`<span class="eyebrow">${shared.length?shared.length+" SHARED INTERESTS":"NEW POSSIBILITY"}</span><h2>${escapeText(p.displayName)}</h2><p class="person-meta">${escapeText(p.city)}, ${escapeText(p.country)} · ${escapeText(p.availability)}</p><p>${escapeText(p.bio)}</p><div class="tags">${(p.interests||[]).map(x=>`<span class="tag">${escapeText(x)}</span>`).join("")}</div><p class="fine">Languages: ${escapeText((p.languages||[]).join(", "))}</p><div class="person-actions"><button class="button connect">Connect</button><button class="danger-link report">Report or block</button></div>`;article.querySelector(".connect").onclick=()=>sendRequest(uid,p);article.querySelector(".report").onclick=()=>openReport(uid,p.displayName);return article}

async function loadBlocked(){const ids=new Set();const [mine,theirs]=await Promise.all([getDocs(query(collection(db,"blocks"),where("blockerId","==",state.user.uid),limit(100))),getDocs(query(collection(db,"blocks"),where("blockedId","==",state.user.uid),limit(100)))]);mine.forEach(x=>ids.add(x.data().blockedId));theirs.forEach(x=>ids.add(x.data().blockerId));return ids}
async function loadProfiles(){if(!state.user||!requireProfile())return;const status=$("#discoverStatus"),container=$("#profiles");status.textContent="Loading profiles…";container.replaceChildren();try{const blocked=await loadBlocked();const snap=await getDocs(query(collection(db,"profiles"),where("active","==",true),limit(60)));state.profiles.clear();snap.forEach(x=>state.profiles.set(x.id,x.data()));const city=$("#filterCity").value.trim().toLowerCase(),interest=$("#filterInterest").value.trim().toLowerCase();const items=[...state.profiles].filter(([uid,p])=>uid!==state.user.uid&&!blocked.has(uid)&&(!city||p.city.toLowerCase().includes(city))&&(!interest||(p.interests||[]).some(x=>x.toLowerCase().includes(interest))));items.forEach(([uid,p])=>container.append(profileCard(uid,p)));status.textContent=items.length?`${items.length} profile${items.length===1?"":"s"} found.`:"No profiles match these filters yet."}catch(error){status.textContent=errorMessage(error)}}

async function sendRequest(uid,profile){if(!requireProfile())return;const id=pairId(state.user.uid,uid);try{const existing=await getDoc(doc(db,"connections",id));if(existing.exists())return toast("A connection record already exists.");await setDoc(doc(db,"connections",id),{participants:[state.user.uid,uid].sort(),requestedBy:state.user.uid,recipientId:uid,status:"pending",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});toast(`Request sent to ${profile.displayName}.`)}catch(error){toast(errorMessage(error))}}

function profileName(uid){return state.profiles.get(uid)?.displayName||"Kindred member"}
function otherId(connection){return connection.participants.find(x=>x!==state.user.uid)}
function connectionRow(connection,mode){const other=otherId(connection),row=document.createElement("article");row.className="connection-row";row.innerHTML=`<div><strong>${escapeText(profileName(other))}</strong><div class="fine">${escapeText(connection.status)}</div></div>`;if(mode==="incoming"){const yes=document.createElement("button");yes.className="button";yes.textContent="Accept";yes.onclick=()=>answerRequest(connection.id,"accepted");const no=document.createElement("button");no.className="secondary";no.textContent="Decline";no.onclick=()=>answerRequest(connection.id,"declined");row.append(yes,no)}if(mode==="accepted"){const msg=document.createElement("button");msg.className="button";msg.textContent="Message";msg.onclick=()=>openConversation(connection);const report=document.createElement("button");report.className="danger-link";report.textContent="Report or block";report.onclick=()=>openReport(other,profileName(other));row.append(msg,report)}return row}
function renderConnections(){const incoming=$("#incoming"),accepted=$("#accepted"),outgoing=$("#outgoing");[incoming,accepted,outgoing].forEach(x=>x.replaceChildren());let incomingCount=0;state.connections.forEach(c=>{if(c.status==="pending"&&c.recipientId===state.user.uid){incoming.append(connectionRow(c,"incoming"));incomingCount++}else if(c.status==="accepted")accepted.append(connectionRow(c,"accepted"));else if(c.status==="pending")outgoing.append(connectionRow(c,"outgoing"))});$("#requestCount").textContent=incomingCount?`(${incomingCount})`:"";if(!incoming.children.length)incoming.innerHTML='<p class="fine">No new requests.</p>';if(!accepted.children.length)accepted.innerHTML='<p class="fine">No accepted connections yet.</p>';if(!outgoing.children.length)outgoing.innerHTML='<p class="fine">No pending sent requests.</p>'}
async function answerRequest(id,status){try{await updateDoc(doc(db,"connections",id),{status,updatedAt:serverTimestamp()});toast(status==="accepted"?"Connection accepted.":"Request declined.")}catch(error){toast(errorMessage(error))}}
function watchConnections(){state.unsubConnections?.();state.unsubConnections=onSnapshot(query(collection(db,"connections"),where("participants","array-contains",state.user.uid)),snap=>{state.connections=snap.docs.map(x=>({id:x.id,...x.data()}));renderConnections();renderConversationList()},error=>toast(errorMessage(error)))}

function renderConversationList(){const list=$("#conversationList");list.replaceChildren();state.connections.filter(x=>x.status==="accepted").forEach(c=>{const b=document.createElement("button");b.className="nav-item";b.textContent=profileName(otherId(c));b.onclick=()=>openConversation(c);list.append(b)});if(!list.children.length)list.innerHTML='<p class="fine">Accept a connection before messaging.</p>'}
function openConversation(connection){showPanel("messages");const other=otherId(connection),panel=$("#conversation");panel.innerHTML=`<h2>${escapeText(profileName(other))}</h2><div id="messageStream" class="messages" aria-live="polite"></div><form id="messageForm" class="message-form"><input id="messageText" maxlength="2000" aria-label="Message" required><button class="button">Send</button></form>`;state.unsubMessages?.();state.unsubMessages=onSnapshot(query(collection(db,"connections",connection.id,"messages"),orderBy("createdAt","asc"),limit(100)),snap=>{const stream=$("#messageStream");stream.replaceChildren();snap.forEach(x=>{const d=x.data(),p=document.createElement("p");p.className="message"+(d.senderId===state.user.uid?" mine":"");p.textContent=d.text;stream.append(p)});stream.scrollTop=stream.scrollHeight},error=>toast(errorMessage(error)));$("#messageForm").onsubmit=async event=>{event.preventDefault();const input=$("#messageText"),text=input.value.trim();if(!text)return;try{await addDoc(collection(db,"connections",connection.id,"messages"),{senderId:state.user.uid,text,createdAt:serverTimestamp()});input.value=""}catch(error){toast(errorMessage(error))}}}

function openReport(uid,name){state.reportTarget=uid;$("#reportTarget").textContent=`Your report about ${name} is private and is not shown to that person.`;$("#reportDialog").showModal()}
async function submitReport(event){if(event.submitter?.value==="cancel")return;event.preventDefault();const details=$("#reportDetails").value.trim(),reason=$("#reportReason").value;if(!reason||details.length<20)return toast("Choose a reason and add at least 20 characters.");try{await addDoc(collection(db,"reports"),{reporterId:state.user.uid,reportedId:state.reportTarget,reason,details,status:"open",createdAt:serverTimestamp()});if($("#alsoBlock").checked)await setDoc(doc(db,"blocks",`${state.user.uid}_${state.reportTarget}`),{blockerId:state.user.uid,blockedId:state.reportTarget,createdAt:serverTimestamp()});$("#reportDialog").close();event.target.reset();toast("Report submitted privately.");loadProfiles()}catch(error){toast(errorMessage(error))}}

$$('[data-view]').forEach(x=>x.addEventListener("click",()=>showPanel(x.dataset.view)));
$$('[data-signin]').forEach(x=>x.addEventListener("click",signIn));
$("#authButton").addEventListener("click",()=>state.user?signOut(auth):signIn());
$("#profileForm").addEventListener("submit",saveProfile);
$("#applyFilters").addEventListener("click",loadProfiles);
$("#refreshProfiles").addEventListener("click",loadProfiles);
$("#reportForm").addEventListener("submit",submitReport);

onAuthStateChanged(auth,async user=>{state.user=user;$("#signedOut").hidden=!!user;$("#signedIn").hidden=!user;$("#authButton").textContent=user?"Sign out":"Sign in with Google";state.unsubMessages?.();state.unsubConnections?.();if(!user){state.profile=null;return}try{await savePrivateUser(user);await loadOwnProfile();watchConnections();await loadProfiles()}catch(error){toast(errorMessage(error))}});
